### ISSUE TITLE
Move/Rename/Create IMAP Folders

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/hm3#60] opened 2016-04-16 13:17 UTC
First i have to say, i <3 your software.

What i would need to replace my email-program is the full imap folder functionality. There is a Tag-Issue aswell - depending how that will work out it might be sufficient aswell.

With the Folder Ability the Possibility to move Messages would be required aswell. If you consider implementing this, i would reccomend to start with this Feature.

If this Feature already exists i could not find it. Point me to it then pls.

Thanks in Advance Ulf

**Comment by jasonmunro** [comment] 2016-04-18 22:17
Thanks for the kind words and feedback! I have started on the ability to move/copy. Don't have an ETA on when it will be done since there are a lot of considerations. For folder management, I think I will create a new module set called "imap_folders" that allows you to create/delete/rename folders. Thanks again for the feedback.

**Comment by ulfgebhardt** [comment] 2016-04-19 05:35
<3 take your time! And if you need anything just say so please.

**Comment by jasonmunro** [comment] 2016-04-25 15:59
The initial version of move/copy is in.  A couple of things to note:

- Move/copy buttons will appear next to the existing message controls once you select a message. They will be in a disabled state unless at least one of the selected messages is an IMAP message.
- Move/copy only works with IMAP messages. If you are in a combined view and select any non-IMAP messages then click move or copy, they will be de-selected and a notice will appear stating so
- Move/copy is disabled on mobile just to keep the UI clean. I will enable it at some point once I work out the layout issues.
- I was able to use some javascript-fu to re-purpose the existing folder list navigation for the destination folder to move/copy to.
- You can move/copy messages to other folders within the same IMAP account, or to a different account/folder. This was tricky, but works pretty slick so far!

When you get a chance to check it out let me know what you think!

**Comment by ulfgebhardt** [comment] 2016-05-07 01:26
Hello, i just pulled your latest master and deployed it onto the server. I reran the config generator and the new features apear when selecting an email in the list.
But using either Move or Copy results in "Unable to move/copy selected Messages". How can i determin the Error? My Mailserver aint showing anything. The Mails are imap.

**Comment by jasonmunro** [comment] 2016-05-09 16:38
Weird, maybe I broke something already! I will try to reproduce this today, and failing that, will add some debugging to the master branch so you can determine where the issue is. Have you tried both moving or copying to the same IMAP account and to a different account? Just curious if both fail.

Thanks for the follow up.

**Comment by ulfgebhardt** [comment] 2016-05-09 16:52
You are right!
Moving Messages between Mailboxes works - within Mailboxes fails tho.

I appriciate the work you do! One more request regarding this
For Useability Purposes, could you add Copy & Move operation to the Message-Operations

`all headers | reply | reply-all | forward | attach | raw | flag | delete | **move | copy** `

Greetings Ulf

**Comment by jasonmunro** [comment] 2016-05-09 17:03
After I wrote this I abstracted some bits out to make the code cleaner, and made some really stupid mistakes in the process :) Should be fixed in the following commit: https://github.com/jasonmunro/hm3/commit/f7b5e13a5a1288864c50e20b8de5b655094e1c87

Great idea to add them to the message view page. I will try to get that added today. Should be able to re-use much of the existing logic (I hope!).

**Comment by jasonmunro** [comment] 2016-05-09 23:05
copy + move have been added to the message view. Thanks for the great idea! The only bit I don't like, is the way the redirect-after-move works.  It's the same redirect that happens when deleting from the message page, and it doesn't maintain the notice about the delete/move success or failure. Working on something to clean that up in the next day or two, maybe a client side message forwarding mechanism.

**Comment by jasonmunro** [comment] 2016-05-11 13:55
Fixed the notice issue after move + redirect. And wrapped up the first version of the imap_folders module set!

Pull the latest code, add "imap_folders" to your list of enabled modules, re-generate the config, and you should have a "folders" page in the settings section of the folder list. From here you can create/rename/delete folders in any of your IMAP accounts.

**Comment by jasonmunro** [comment] 2016-05-25 20:41
closing this for now since it's "working for me" :) If you have issues please re-open ore create a new issue. Thanks!

**Closed** 2016-05-25 20:41 UTC
Labels: enhancement, imap, imap_folders

**Comment by ulfgebhardt** [comment] 2016-05-26 17:18
Im sorry it took so long for me to answer.
I just updated to the latest version. All works fine as you described it.
Consider putting the "imap_folders" module in default config if u havent done so alrdy.

Thank you so much for this - this is all i needed! <3

**Comment by jasonmunro** [comment] 2016-05-26 17:23
Just added the module to the default config, thanks for catching that. And thanks for the follow up, it's appreciated!
